eureka:
  instance:
    hostname: localhost
    metadata-map:
      appOwner: ${project.organization.name}
      description: ${project.description}
    #    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    statusPageUrlPath: /
  #    health-check-url-path: /health
  client:
    service-url:
      defaultZone: ${em.eureka-server.replicas}