project:
  organization:
    name: Eager Minds

em:
  config-server:
    hostname: localhost
    port: 8888
  eureka-server:
    replicas: ${EUREKA_URI:http://${em.eureka-server.peer1.address}/eureka},${EUREKA_URI:http://${em.eureka-server.peer2.address}/eureka},${EUREKA_URI:http://${em.eureka-server.peer3.address}/eureka}
    user:
      name: admin
      password: pwd
    peer1:
      hostname: localhost
      port: 8761
      address: ${em.eureka-server.user.name}:${em.eureka-server.user.password}@${em.eureka-server.peer1.hostname}:${em.eureka-server.peer1.port}
    peer2:
      hostname: localhost
      port: 8762
      address: ${em.eureka-server.user.name}:${em.eureka-server.user.password}@${em.eureka-server.peer2.hostname}:${em.eureka-server.peer2.port}
    peer3:
      hostname: localhost
      port: 8763
      address: ${em.eureka-server.user.name}:${em.eureka-server.user.password}@${em.eureka-server.peer3.hostname}:${em.eureka-server.peer3.port}
  auth-server:
    appName: auth-server
    hostname: localhost
    port: 8000

spring:
  banner:
    image:
      location: em_banner.png
      width: 76
      height: 32
      invert: true

logging:
  level:
    liquibase: INFO
    org:
      springframework:
        security: DEBUG
        cloud: DEBUG
    com:
      netflix:
        eureka: OFF
        discovery: OFF

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  #    shutdown:
  #      enabled: true
  endpoints:
    web:
      #      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'

eureka:
  instance:
    #    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    statusPageUrlPath: /
  #    health-check-url-path: /health
  client:
    service-url:
      defaultZone: ${em.eureka-server.replicas}