em:
  serverConfig:
    replicas: ${EUREKA_URI:http://${em.serverConfig.peer1.address}/eureka},${EUREKA_URI:http://${em.serverConfig.peer2.address}/eureka},${EUREKA_URI:http://${em.serverConfig.peer3.address}/eureka}
    user:
      name: admin
      password: pwd
    peer1:
      hostname: localhost
      port: 8761
      address: ${em.serverConfig.user.name}:${em.serverConfig.user.password}@${em.serverConfig.peer1.hostname}:${em.serverConfig.peer1.port}
    peer2:
      hostname: localhost
      port: 8762
      address: ${em.serverConfig.user.name}:${em.serverConfig.user.password}@${em.serverConfig.peer2.hostname}:${em.serverConfig.peer2.port}
    peer3:
      hostname: localhost
      port: 8763
      address: ${em.serverConfig.user.name}:${em.serverConfig.user.password}@${em.serverConfig.peer3.hostname}:${em.serverConfig.peer3.port}
  auth-server:
    appName: auth-server
    hostname: localhost
    port: 8000

server:
  port: ${em.auth-server.port}

spring:
  application:
    name: ${project.artifactId}
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: pwd
  banner:
    image:
      location: em_banner.png
      width: 76
      height: 32
      invert: true

logging:
  level:
    liquibase: INFO

eureka:
  instance:
    metadata-map:
      appOwner: ${project.organization.name}
      description: ${project.description}
    hostname: ${em.auth-server.hostname}
    #    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    statusPageUrlPath: /
  #    health-check-url-path: /health
  client:
    service-url:
      defaultZone: ${em.serverConfig.replicas}

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:./db/h2/DB
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;

