project:
  artifactId: auth-server
  name: Authentication Server
  description: ${project.name}

server:
  port: ${em.auth-server.port}

spring:
  application:
    name: ${project.artifactId}
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: pwd
  banner:
    image:
      location: em_banner.png
      width: 76
      height: 32
      invert: true

logging:
  level:
    liquibase: INFO

eureka:
  instance:
    metadata-map:
      appOwner: ${project.organization.name}
      description: ${project.description}
    hostname: ${em.auth-server.hostname}
    #    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    statusPageUrlPath: /
  #    health-check-url-path: /health

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:./db/h2/DB
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;

