project:
  artifactId: auth-server
  name: Authentication Server
  description: ${project.name}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: user
    password: pwd

eureka:
  instance:
    metadata-map:
      appOwner: ${project.organization.name}
      description: ${project.description}
    hostname: ${em.auth-server.hostname}

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:file:./db/h2/DB
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;

