project:
  artifactId: config-server
  name: Configuration Server
  description: ${project.name}

eureka:
  instance:
    metadata-map:
      appOwner: ${project.organization.name}
      description: ${project.description}
    hostname: ${em.eureka-server.hostname}