project:
  artifactId: config-server
  name: Configuration Server
  description: ${project.name}

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  security:
    user:
      name: admin
      password: pwd

eureka:
  instance:
    metadata-map:
      appOwner: ${project.organization.name}
      description: ${project.description}
    hostname: ${em.eureka-server.hostname}