em.hostname: ${em.eureka-server.peer1.hostname}
project:
  artifactId: eureka-server
  name: Eureka Server
  description: ${project.name}

spring:
  security:
    user:
      name: ${em.spring.security.user.name}
      password: ${em.spring.security.user.password}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
---
em.hostname: ${em.eureka-server.peer1.hostname}
spring:
  profiles: peer1
server:
  port: ${em.eureka-server.peer1.port}

---
em.hostname: ${em.eureka-server.peer2.hostname}
spring:
  profiles: peer2
server:
  port: ${em.eureka-server.peer2.port}

---
em.hostname: ${em.eureka-server.peer3.hostname}
#    appname: ${em.eureka-server.appName}-${em.eureka-server.peer3.hostname}
spring:
  profiles: peer3
server:
  port: ${em.eureka-server.peer3.port}

