project:
  artifactId: eureka-server
  name: Eureka Server
  description: ${project.name}

spring:
  security:
    user:
      name: ${em.spring.security.user.name}
      password: ${em.spring.security.user.password}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: eureka-client

eureka:
  instance:
    hostname: ${em.eureka-server.hostname}
    appname: eureka-server
    metadataMap:
      user:
        name: ${em.eureka-server.user.name}
        password: ${em.eureka-server.user.password}
      appOwner: ${project.organization.name}
      description: ${project.description}
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
    enableSelfPreservation: true
#    wait-time-in-ms-when-sync-empty: 0

---
em.eureka-server.hostname: ${em.eureka-server.peer1.hostname}
spring:
  profiles: peer1
server:
  port: ${em.eureka-server.peer1.port}
eureka:
  instance:
    hostname: ${em.eureka-server.peer1.hostname}

---
em.eureka-server.hostname: ${em.eureka-server.peer2.hostname}
spring:
  profiles: peer2
server:
  port: ${em.eureka-server.peer2.port}
eureka:
  instance:
    hostname: ${em.eureka-server.peer2.hostname}

---
em.eureka-server.hostname: ${em.eureka-server.peer3.hostname}
spring:
  profiles: peer3
server:
  port: ${em.eureka-server.peer3.port}
eureka:
  instance:
    #    appname: ${em.eureka-server.appName}-${em.eureka-server.peer3.hostname}
    hostname: ${em.eureka-server.peer3.hostname}

