project:
  artifactId: eureka-server
  name: Eureka Server
  description: ${project.name}
  version: 1.0-SNAPSHOT

spring:
  security:
    user:
      name: ${em.spring.security.user.name}
      password: ${em.spring.security.user.password}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
